"""initial_schema

Revision ID: 05f58450e8f9
Revises: 
Create Date: 2026-03-27 14:42:39.868181

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05f58450e8f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screening_requests',
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('project_type', sa.Enum('ROAD', 'HOUSING', 'POWER_PLANT', 'FACTORY', 'OTHER', name='project_type'), nullable=False),
    sa.Column('project_scale', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('llm_interpretation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # GeoAlchemy2 auto-creates GIST indexes for Geometry columns
    op.create_table('regulation_matches',
    sa.Column('screening_request_id', sa.UUID(), nullable=False),
    sa.Column('regulation_name', sa.String(length=200), nullable=False),
    sa.Column('regulation_code', sa.String(length=50), nullable=True),
    sa.Column('legal_basis', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('restriction_level', sa.String(length=50), nullable=True),
    sa.Column('permit_required', sa.Boolean(), nullable=False),
    sa.Column('related_authority', sa.String(length=200), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['screening_request_id'], ['screening_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_cards',
    sa.Column('screening_request_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('rule_version', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'MAJOR', 'REVIEW', 'INFO', name='severity'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('legal_basis', sa.String(length=300), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('human_review_required', sa.Boolean(), nullable=False),
    sa.Column('trigger_dataset', sa.String(length=100), nullable=True),
    sa.Column('source_snapshot_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['screening_request_id'], ['screening_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_cards')
    op.drop_table('regulation_matches')
    op.drop_table('screening_requests')
    # ### end Alembic commands ###
